### ISSUE TITLE
datetime not show in cosmos os help!

### ISSUE THREAD

**Issue by HESAMOSTAD** [HESAMOSTAD/RAGON_OS_VER_0.002#1]
Hello I write a RAGON_OS (Last 5 word of dragon) with cosmos userkit in vs2015 i try every datetime
public static void time() //in commands.cs
{
 Console.Write("Current Date and Time is : ");
            DateTime now = DateTime.Now;
            Console.WriteLine(now);
            Console.ReadLine();
}
and in kernel.cs i write a switch cases you can see it in file
switch "time":
commands.time();
break;
it dont say any error but when i press start
 but it dont run because il2cpu. can anyone give me the source code please?

**Comment by GeorgeFence** [comment]
Try using DevKit, Userkit is outdated and not working very well

**Comment by GeorgeFence** [comment]
Or just replace 
_DateTime now = DateTime.Now;
Console.WriteLine(now);_
 
To

_Console.WriteLine(DateTime.Now.Tostring());_

**Comment by GeorgeFence** [comment]
Or just replace 
_DateTime now = DateTime.Now;
Console.WriteLine(now);_
 
To

_Console.WriteLine(DateTime.Now.Tostring());_

**Comment by HESAMOSTAD** [comment]
OK thanks for your help I will try.
